// generated by Stubber

@import Foundation;
// category - class exists but is missing selectors
@interface CWNetwork:NSObject
@end
@interface CWNetwork(Stub)
@end
@implementation CWNetwork(Stub)
// matchesKnownNetworkSecurity: c c24@0:8q16
-(char)matchesKnownNetworkSecurity:(long long)arg2
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWWiFiClient:NSObject
@end
@interface CWWiFiClient(Stub)
@end
@implementation CWWiFiClient(Stub)
// btCoexModeStats: v v24@0:8@16
-(void)btCoexModeStats:(id)arg2
{
	return ;
}
// internal_receivedAutoHotspotNotificationResponse:updateMode:tetherDevice:authorization:interfaceName:error: c c60@0:8c16q20@28@36@44^@52
-(char)internal_receivedAutoHotspotNotificationResponse:(char)arg2 updateMode:(long long)arg3 tetherDevice:(id)arg4 authorization:(id)arg5 interfaceName:(id)arg6 error:(void*)arg7
{
	return 0;
}
// joinDidCompleteForWiFiInterfaceWithName:isAutoJoin:error: v v36@0:8@16c24@28
-(void)joinDidCompleteForWiFiInterfaceWithName:(id)arg2 isAutoJoin:(char)arg3 error:(id)arg4
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWInterface:NSObject
@end
@interface CWInterface(Stub)
@end
@implementation CWInterface(Stub)
// awdlServiceManager @ @16@0:8
-(id)awdlServiceManager
{
	return nil;
}
// setAwdlServiceManager: v v24@0:8@16
-(void)setAwdlServiceManager:(id)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWNetworkProfile:NSObject
@end
@interface CWNetworkProfile(Stub)
@end
@implementation CWNetworkProfile(Stub)
// setLowDataMode: v v24@0:8Q16
-(void)setLowDataMode:(unsigned long long)arg2
{
	return ;
}
// coreWiFiSpecificAttributes @ @16@0:8
-(id)coreWiFiSpecificAttributes
{
	return nil;
}
// lowDataMode Q Q16@0:8
-(unsigned long long)lowDataMode
{
	return 0;
}
// setCoreWiFiSpecificAttributes: v v24@0:8@16
-(void)setCoreWiFiSpecificAttributes:(id)arg2
{
	return ;
}
// setStandalone6G: v v20@0:8c16
-(void)setStandalone6G:(char)arg2
{
	return ;
}
// setTransitionDisabledFlags: v v24@0:8Q16
-(void)setTransitionDisabledFlags:(unsigned long long)arg2
{
	return ;
}
// standalone6G c c16@0:8
-(char)standalone6G
{
	return 0;
}
// transitionDisabledFlags Q Q16@0:8
-(unsigned long long)transitionDisabledFlags
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWTrimmedNetwork:NSObject
@end
@interface CWTrimmedNetwork(Stub)
@end
@implementation CWTrimmedNetwork(Stub)
// matchesKnownNetworkSecurity: c c24@0:8q16
-(char)matchesKnownNetworkSecurity:(long long)arg2
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWWiFiUIProxyClient:NSObject
@end
@interface CWWiFiUIProxyClient(Stub)
@end
@implementation CWWiFiUIProxyClient(Stub)
// showLimitedNetworkOptionUIForScanResult:candidates:uuid: v v40@0:8@16@24@32
-(void)showLimitedNetworkOptionUIForScanResult:(id)arg2 candidates:(id)arg3 uuid:(id)arg4
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWRoamStatistics:NSObject
@end
@interface CWRoamStatistics(Stub)
@end
@implementation CWRoamStatistics(Stub)
// active6GHzProfile q q16@0:8
-(long long)active6GHzProfile
{
	return 0;
}
// setActive6GHzProfile: v v24@0:8q16
-(void)setActive6GHzProfile:(long long)arg2
{
	return ;
}
@end
NSString* kWiFiAutoJoinPowerDiagnosticsKey=@"kWiFiAutoJoinPowerDiagnosticsKey";
