// generated by Stubber

@import Foundation;
// stub - class doesn't exist at all
@interface CWFRNRBSS:NSObject
{
	char _UPRActive;
	char _sameSSID;
	char _multipleBSSID;
	char _transmittedBSSID;
	char _multiband6GHz;
	char _colocatedAP;
	unsigned long long _shortSSID;
	id _BSSID;
	id _channel;
	unsigned long long _TBTTOffset;
	unsigned long long _primary20MHzPSD;
}
@end
@implementation CWFRNRBSS
// copyWithZone: @ @24@0:8^{_NSZone=}16
-(id)copyWithZone:(void*)arg2
{
	return nil;
}
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// .cxx_destruct v v16@0:8
// skipped - in banned method list
// encodeWithCoder: v v24@0:8@16
-(void)encodeWithCoder:(id)arg2
{
	return ;
}
// initWithCoder: @ @24@0:8@16
-(id)initWithCoder:(id)arg2
{
	return nil;
}
// channel @ @16@0:8
-(id)channel
{
	return nil;
}
// BSSID @ @16@0:8
-(id)BSSID
{
	return nil;
}
// setBSSID: v v24@0:8@16
-(void)setBSSID:(id)arg2
{
	return ;
}
// setChannel: v v24@0:8@16
-(void)setChannel:(id)arg2
{
	return ;
}
// isMultiband6GHz c c16@0:8
-(char)isMultiband6GHz
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// setColocatedAP: v v20@0:8c16
-(void)setColocatedAP:(char)arg2
{
	return ;
}
// isMultipleBSSID c c16@0:8
-(char)isMultipleBSSID
{
	return 0;
}
// primary20MHzPSD Q Q16@0:8
-(unsigned long long)primary20MHzPSD
{
	return 0;
}
// TBTTOffset Q Q16@0:8
-(unsigned long long)TBTTOffset
{
	return 0;
}
// isColocatedAP c c16@0:8
-(char)isColocatedAP
{
	return 0;
}
// isEqualToRNRBSS: c c24@0:8@16
-(char)isEqualToRNRBSS:(id)arg2
{
	return 0;
}
// isSameSSID c c16@0:8
-(char)isSameSSID
{
	return 0;
}
// isTransmittedBSSID c c16@0:8
-(char)isTransmittedBSSID
{
	return 0;
}
// isUPRActive c c16@0:8
-(char)isUPRActive
{
	return 0;
}
// setMultiband6GHz: v v20@0:8c16
-(void)setMultiband6GHz:(char)arg2
{
	return ;
}
// setMultipleBSSID: v v20@0:8c16
-(void)setMultipleBSSID:(char)arg2
{
	return ;
}
// setPrimary20MHzPSD: v v24@0:8Q16
-(void)setPrimary20MHzPSD:(unsigned long long)arg2
{
	return ;
}
// setSameSSID: v v20@0:8c16
-(void)setSameSSID:(char)arg2
{
	return ;
}
// setShortSSID: v v24@0:8Q16
-(void)setShortSSID:(unsigned long long)arg2
{
	return ;
}
// setTBTTOffset: v v24@0:8Q16
-(void)setTBTTOffset:(unsigned long long)arg2
{
	return ;
}
// setTransmittedBSSID: v v20@0:8c16
-(void)setTransmittedBSSID:(char)arg2
{
	return ;
}
// setUPRActive: v v20@0:8c16
-(void)setUPRActive:(char)arg2
{
	return ;
}
// shortSSID Q Q16@0:8
-(unsigned long long)shortSSID
{
	return 0;
}
// supportsSecureCoding c c16@0:8
+(char)supportsSecureCoding
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFAutoJoinParameters:NSObject
@end
@interface CWFAutoJoinParameters(Stub)
@end
@implementation CWFAutoJoinParameters(Stub)
// preferredChannels @ @16@0:8
-(id)preferredChannels
{
	return nil;
}
// setPreferredChannels: v v24@0:8@16
-(void)setPreferredChannels:(id)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFLinkChangeStatus:NSObject
@end
@interface CWFLinkChangeStatus(Stub)
@end
@implementation CWFLinkChangeStatus(Stub)
// isLinkDownDebounceInProgress c c16@0:8
-(char)isLinkDownDebounceInProgress
{
	return 0;
}
// setLinkDownDebounceInProgress: v v20@0:8c16
-(void)setLinkDownDebounceInProgress:(char)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFXPCConnection:NSObject
@end
@interface CWFXPCConnection(Stub)
@end
@implementation CWFXPCConnection(Stub)
// __allowAlreadyPendingRequest: c c24@0:8@16
-(char)__allowAlreadyPendingRequest:(id)arg2
{
	return 0;
}
// __hasPendingRequestWithType: c c24@0:8q16
-(char)__hasPendingRequestWithType:(long long)arg2
{
	return 0;
}
// __perform6GHzFollowupScanAndAssociateWithParameters:BSS:parentXPCRequest: v v40@0:8@16@24@32
-(void)__perform6GHzFollowupScanAndAssociateWithParameters:(id)arg2 BSS:(id)arg3 parentXPCRequest:(id)arg4
{
	return ;
}
// __performFollowupANQPForPasspointScanResults:combinedScanResults:parameters:parentXPCRequest: v v48@0:8@16@24@32@40
-(void)__performFollowupANQPForPasspointScanResults:(id)arg2 combinedScanResults:(id)arg3 parameters:(id)arg4 parentXPCRequest:(id)arg5
{
	return ;
}
// __shouldPerformPreAssociation6GHzFollowupScan: @ @24@0:8@16
-(id)__shouldPerformPreAssociation6GHzFollowupScan:(id)arg2
{
	return nil;
}
// performSensingWithParameters:requestParams:reply: v v40@0:8@16@24@?32
-(void)performSensingWithParameters:(id)arg2 requestParams:(id)arg3 reply:(id)arg4
{
	return ;
}
// queryAutoJoinMetricWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryAutoJoinMetricWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryAutoJoinStatisticsWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryAutoJoinStatisticsWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryCountryBandSupport:reply: v v32@0:8@16@?24
-(void)queryCountryBandSupport:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryDHCPServerIDWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryDHCPServerIDWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryDHCPv6ServerIDWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryDHCPv6ServerIDWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryIPv4ARPResolvedHardwareAddressWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryIPv4ARPResolvedHardwareAddressWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryIPv4ARPResolvedIPAddressWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryIPv4ARPResolvedIPAddressWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryIPv4NetworkSignatureWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryIPv4NetworkSignatureWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryIPv4SubnetMasksWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryIPv4SubnetMasksWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryIPv6NetworkSignatureWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryIPv6NetworkSignatureWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// queryUserSettingsWithRequestParams:reply: v v32@0:8@16@?24
-(void)queryUserSettingsWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// resetAutoJoinStatisticsWithRequestParams:reply: v v32@0:8@16@?24
-(void)resetAutoJoinStatisticsWithRequestParams:(id)arg2 reply:(id)arg3
{
	return ;
}
// setUserSettings:properties:requestParams:reply: v v48@0:8@16@24@32@?40
-(void)setUserSettings:(id)arg2 properties:(id)arg3 requestParams:(id)arg4 reply:(id)arg5
{
	return ;
}
@end
// stub - class doesn't exist at all
@interface CWFUserSettings:NSObject
{
	long long _syncMode;
	long long _askToJoinMode;
	long long _autoHotspotMode;
	long long _compatibilityMode;
	id _OSSpecificAttributes;
}
@end
@implementation CWFUserSettings
// copyWithZone: @ @24@0:8^{_NSZone=}16
-(id)copyWithZone:(void*)arg2
{
	return nil;
}
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// .cxx_destruct v v16@0:8
// skipped - in banned method list
// encodeWithCoder: v v24@0:8@16
-(void)encodeWithCoder:(id)arg2
{
	return ;
}
// initWithCoder: @ @24@0:8@16
-(id)initWithCoder:(id)arg2
{
	return nil;
}
// autoHotspotMode q q16@0:8
-(long long)autoHotspotMode
{
	return 0;
}
// OSSpecificAttributes @ @16@0:8
-(id)OSSpecificAttributes
{
	return nil;
}
// setOSSpecificAttributes: v v24@0:8@16
-(void)setOSSpecificAttributes:(id)arg2
{
	return ;
}
// askToJoinMode q q16@0:8
-(long long)askToJoinMode
{
	return 0;
}
// compatibilityMode q q16@0:8
-(long long)compatibilityMode
{
	return 0;
}
// isEqualToUserSettings: c c24@0:8@16
-(char)isEqualToUserSettings:(id)arg2
{
	return 0;
}
// setAskToJoinMode: v v24@0:8q16
-(void)setAskToJoinMode:(long long)arg2
{
	return ;
}
// setAutoHotspotMode: v v24@0:8q16
-(void)setAutoHotspotMode:(long long)arg2
{
	return ;
}
// setCompatibilityMode: v v24@0:8q16
-(void)setCompatibilityMode:(long long)arg2
{
	return ;
}
// setSyncMode: v v24@0:8q16
-(void)setSyncMode:(long long)arg2
{
	return ;
}
// syncMode q q16@0:8
-(long long)syncMode
{
	return 0;
}
// supportsSecureCoding c c16@0:8
+(char)supportsSecureCoding
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFRoamStatus:NSObject
@end
@interface CWFRoamStatus(Stub)
@end
@implementation CWFRoamStatus(Stub)
// duration d d16@0:8
-(double)duration
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// descriptionForRoamReason @ @16@0:8
-(id)descriptionForRoamReason
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFAssocParameters:NSObject
@end
@interface CWFAssocParameters(Stub)
@end
@implementation CWFAssocParameters(Stub)
// bandPreference q q16@0:8
-(long long)bandPreference
{
	return 0;
}
// colocatedScopeID @ @16@0:8
-(id)colocatedScopeID
{
	return nil;
}
// forceBSSID c c16@0:8
-(char)forceBSSID
{
	return 0;
}
// setBandPreference: v v24@0:8q16
-(void)setBandPreference:(long long)arg2
{
	return ;
}
// setColocatedScopeID: v v24@0:8@16
-(void)setColocatedScopeID:(id)arg2
{
	return ;
}
// setForceBSSID: v v20@0:8c16
-(void)setForceBSSID:(char)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFAWDLPeerTrafficRegistration:NSObject
@end
@interface CWFAWDLPeerTrafficRegistration(Stub)
@end
@implementation CWFAWDLPeerTrafficRegistration(Stub)
// serializedRegistrationInfo @ @16@0:8
-(id)serializedRegistrationInfo
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFAutoJoinStatus:NSObject
@end
@interface CWFAutoJoinStatus(Stub)
@end
@implementation CWFAutoJoinStatus(Stub)
// duration d d16@0:8
-(double)duration
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFBSS:NSObject
@end
@interface CWFBSS(Stub)
@end
@implementation CWFBSS(Stub)
// description @ @16@0:8
// skipped - implemented in superclass
// AWDLRealTimeModeTimestamp @ @16@0:8
-(id)AWDLRealTimeModeTimestamp
{
	return nil;
}
// DHCPServerID @ @16@0:8
-(id)DHCPServerID
{
	return nil;
}
// IPv6NetworkSignature @ @16@0:8
-(id)IPv6NetworkSignature
{
	return nil;
}
// DHCPv6ServerID @ @16@0:8
-(id)DHCPv6ServerID
{
	return nil;
}
// IPv4NetworkSignature @ @16@0:8
-(id)IPv4NetworkSignature
{
	return nil;
}
// colocated2GHzRNRChannel @ @16@0:8
-(id)colocated2GHzRNRChannel
{
	return nil;
}
// colocated5GHzRNRChannel @ @16@0:8
-(id)colocated5GHzRNRChannel
{
	return nil;
}
// coreWiFiSpecificAttributes @ @16@0:8
-(id)coreWiFiSpecificAttributes
{
	return nil;
}
// setAWDLRealTimeModeTimestamp: v v24@0:8@16
-(void)setAWDLRealTimeModeTimestamp:(id)arg2
{
	return ;
}
// setColocated2GHzRNRChannel: v v24@0:8@16
-(void)setColocated2GHzRNRChannel:(id)arg2
{
	return ;
}
// setColocated5GHzRNRChannel: v v24@0:8@16
-(void)setColocated5GHzRNRChannel:(id)arg2
{
	return ;
}
// setCoreWiFiSpecificAttributes: v v24@0:8@16
-(void)setCoreWiFiSpecificAttributes:(id)arg2
{
	return ;
}
// setDHCPServerID: v v24@0:8@16
-(void)setDHCPServerID:(id)arg2
{
	return ;
}
// setDHCPv6ServerID: v v24@0:8@16
-(void)setDHCPv6ServerID:(id)arg2
{
	return ;
}
// setIPv4NetworkSignature: v v24@0:8@16
-(void)setIPv4NetworkSignature:(id)arg2
{
	return ;
}
// setIPv6NetworkSignature: v v24@0:8@16
-(void)setIPv6NetworkSignature:(id)arg2
{
	return ;
}
// __coreWiFiSpecificKeys @ @16@0:8
-(id)__coreWiFiSpecificKeys
{
	return nil;
}
// __updateWithExternalForm: v v24@0:8@16
-(void)__updateWithExternalForm:(id)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFAutoJoinManager:NSObject
@end
@interface CWFAutoJoinManager(Stub)
@end
@implementation CWFAutoJoinManager(Stub)
// statistics @ @16@0:8
-(id)statistics
{
	return nil;
}
// metric @ @16@0:8
-(id)metric
{
	return nil;
}
// resetStatistics v v16@0:8
-(void)resetStatistics
{
	return ;
}
// __retryTriggerForRetrySchedule: q q24@0:8q16
-(long long)__retryTriggerForRetrySchedule:(long long)arg2
{
	return 0;
}
// __retryInterval @ @16@0:8
-(id)__retryInterval
{
	return nil;
}
// __addDependentThrottleInterval:trigger:dependentTrigger: v v40@0:8Q16q24q32
-(void)__addDependentThrottleInterval:(unsigned long long)arg2 trigger:(long long)arg3 dependentTrigger:(long long)arg4
{
	return ;
}
// __addMatchingThrottleInterval:triggers: v v32@0:8Q16@24
-(void)__addMatchingThrottleInterval:(unsigned long long)arg2 triggers:(id)arg3
{
	return ;
}
// __addWilcardThrottleInterval:triggers: v v32@0:8Q16@24
-(void)__addWilcardThrottleInterval:(unsigned long long)arg2 triggers:(id)arg3
{
	return ;
}
// __allowJoinCandidate:trigger:defer:error: c c48@0:8@16q24^c32^@40
-(char)__allowJoinCandidate:(id)arg2 trigger:(long long)arg3 defer:(void*)arg4 error:(void*)arg5
{
	return 0;
}
// __allowKnownNetwork:trigger:allowForSeamlessSSIDTransition:defer:error: c c56@0:8@16q24@32^c40^@48
-(char)__allowKnownNetwork:(id)arg2 trigger:(long long)arg3 allowForSeamlessSSIDTransition:(id)arg4 defer:(void*)arg5 error:(void*)arg6
{
	return 0;
}
// __allowOpportunisticNetworkTransitionWithTrigger: c c24@0:8q16
-(char)__allowOpportunisticNetworkTransitionWithTrigger:(long long)arg2
{
	return 0;
}
// __applyRetryIntervalSkew: Q Q24@0:8Q16
-(unsigned long long)__applyRetryIntervalSkew:(unsigned long long)arg2
{
	return 0;
}
// __cachedScanResultsWithChannelList:maxCacheAge:ANQPElementIDList:maxANQPCacheAge: @ @48@0:8@16Q24@32Q40
-(id)__cachedScanResultsWithChannelList:(id)arg2 maxCacheAge:(unsigned long long)arg3 ANQPElementIDList:(id)arg4 maxANQPCacheAge:(unsigned long long)arg5
{
	return nil;
}
// __calloutToAllowJoinCandidate:trigger:defer:error: c c48@0:8@16q24^c32^@40
-(char)__calloutToAllowJoinCandidate:(id)arg2 trigger:(long long)arg3 defer:(void*)arg4 error:(void*)arg5
{
	return 0;
}
// __calloutToAllowKnownNetwork:trigger:allowForSeamlessSSIDTransition:defer:error: c c56@0:8@16q24@32^c40^@48
-(char)__calloutToAllowKnownNetwork:(id)arg2 trigger:(long long)arg3 allowForSeamlessSSIDTransition:(id)arg4 defer:(void*)arg5 error:(void*)arg6
{
	return 0;
}
// __calloutToAssociateWithParameters:error: c c32@0:8@16^@24
-(char)__calloutToAssociateWithParameters:(id)arg2 error:(void*)arg3
{
	return 0;
}
// __candidateSupportsSeamlessSSIDTransition:fromNetwork:trigger: c c40@0:8@16@24q32
-(char)__candidateSupportsSeamlessSSIDTransition:(id)arg2 fromNetwork:(id)arg3 trigger:(long long)arg4
{
	return 0;
}
// __isAutoJoinRequeued c c16@0:8
-(char)__isAutoJoinRequeued
{
	return 0;
}
// __knownNetworksList:containsMatchingKnownNetwork: @ @32@0:8@16@24
-(id)__knownNetworksList:(id)arg2 containsMatchingKnownNetwork:(id)arg3
{
	return nil;
}
// __knownNetworksSupportingSeamlessSSIDTransition:fromNetwork:allowSameSSID:trigger: @ @44@0:8@16@24c32q36
-(id)__knownNetworksSupportingSeamlessSSIDTransition:(id)arg2 fromNetwork:(id)arg3 allowSameSSID:(char)arg4 trigger:(long long)arg5
{
	return nil;
}
// __morePreferredKnownNetworksWithCandidate:knownNetworks:trigger: @ @40@0:8@16@24q32
-(id)__morePreferredKnownNetworksWithCandidate:(id)arg2 knownNetworks:(id)arg3 trigger:(long long)arg4
{
	return nil;
}
// __nextRequestInterval Q Q16@0:8
-(unsigned long long)__nextRequestInterval
{
	return 0;
}
// __perform6GHzFollowupDiscoveryWithScanResults:SSIDList:dwellTime:context:error: @ @56@0:8@16@24Q32@40^@48
-(id)__perform6GHzFollowupDiscoveryWithScanResults:(id)arg2 SSIDList:(id)arg3 dwellTime:(unsigned long long)arg4 context:(id)arg5 error:(void*)arg6
{
	return nil;
}
// __performJoinWithNetwork:context:error: c c40@0:8@16@24^@32
-(char)__performJoinWithNetwork:(id)arg2 context:(id)arg3 error:(void*)arg4
{
	return 0;
}
// __performScanWithChannelList:SSIDList:passive:dwellTime:maxCacheAge:cacheOnly:isPreAssociationScan:error: @ @68@0:8@16@24c32Q36Q44c52c56^@60
-(id)__performScanWithChannelList:(id)arg2 SSIDList:(id)arg3 passive:(char)arg4 dwellTime:(unsigned long long)arg5 maxCacheAge:(unsigned long long)arg6 cacheOnly:(char)arg7 isPreAssociationScan:(char)arg8 error:(void*)arg9
{
	return nil;
}
// __preflightMatchKnownNetworksForScanResult: c c24@0:8@16
-(char)__preflightMatchKnownNetworksForScanResult:(id)arg2
{
	return 0;
}
// __removeRedundantRequests: v v24@0:8@16
-(void)__removeRedundantRequests:(id)arg2
{
	return ;
}
// __setupRetryIntervals v v16@0:8
-(void)__setupRetryIntervals
{
	return ;
}
// __setupThrottleIntervals v v16@0:8
-(void)__setupThrottleIntervals
{
	return ;
}
// __shouldAllowAutoHotspotForTrigger: c c24@0:8q16
-(char)__shouldAllowAutoHotspotForTrigger:(long long)arg2
{
	return 0;
}
// __shouldAllowPreAssocScan c c16@0:8
-(char)__shouldAllowPreAssocScan
{
	return 0;
}
// __shouldBypassUnusedNetworkPeriodCheckForTrigger: c c24@0:8q16
-(char)__shouldBypassUnusedNetworkPeriodCheckForTrigger:(long long)arg2
{
	return 0;
}
// __shouldIgnoreRequestWithTrigger: c c24@0:8q16
-(char)__shouldIgnoreRequestWithTrigger:(long long)arg2
{
	return 0;
}
// __shouldInvokeImmediatelyForTrigger: c c24@0:8q16
-(char)__shouldInvokeImmediatelyForTrigger:(long long)arg2
{
	return 0;
}
// __shouldPrioritizeRetryOverNewRequest: c c24@0:8q16
-(char)__shouldPrioritizeRetryOverNewRequest:(long long)arg2
{
	return 0;
}
// __shouldThrottleAutoJoinTrigger: c c24@0:8q16
-(char)__shouldThrottleAutoJoinTrigger:(long long)arg2
{
	return 0;
}
// __sortJoinCandidates:context: v v32@0:8@16@24
-(void)__sortJoinCandidates:(id)arg2 context:(id)arg3
{
	return ;
}
// __sortKnownNetworksByJoinTimestamp: v v24@0:8@16
-(void)__sortKnownNetworksByJoinTimestamp:(id)arg2
{
	return ;
}
// __updateCachedMetricAndStatistics: v v24@0:8@16
-(void)__updateCachedMetricAndStatistics:(id)arg2
{
	return ;
}
// __updateNextRequestTimer v v16@0:8
-(void)__updateNextRequestTimer
{
	return ;
}
// __updateRNRChannel:joinCandidate: v v32@0:8@16@24
-(void)__updateRNRChannel:(id)arg2 joinCandidate:(id)arg3
{
	return ;
}
// __updateStatisticsWithPreAssocScanChannels: v v24@0:8@16
-(void)__updateStatisticsWithPreAssocScanChannels:(id)arg2
{
	return ;
}
// __updateStatisticsWithScanChannels: v v24@0:8@16
-(void)__updateStatisticsWithScanChannels:(id)arg2
{
	return ;
}
// colocatedScopeID @ @16@0:8
-(id)colocatedScopeID
{
	return nil;
}
// maxCompatibilityEnabled c c16@0:8
-(char)maxCompatibilityEnabled
{
	return 0;
}
// setColocatedScopeID: v v24@0:8@16
-(void)setColocatedScopeID:(id)arg2
{
	return ;
}
// setMaxCompatibilityEnabled: v v20@0:8c16
-(void)setMaxCompatibilityEnabled:(char)arg2
{
	return ;
}
@end
// stub - class doesn't exist at all
@interface CWFSensingResult:NSObject
{
	id _data;
}
@end
@implementation CWFSensingResult
// copyWithZone: @ @24@0:8^{_NSZone=}16
-(id)copyWithZone:(void*)arg2
{
	return nil;
}
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// .cxx_destruct v v16@0:8
// skipped - in banned method list
// data @ @16@0:8
-(id)data
{
	return nil;
}
// encodeWithCoder: v v24@0:8@16
-(void)encodeWithCoder:(id)arg2
{
	return ;
}
// initWithCoder: @ @24@0:8@16
-(id)initWithCoder:(id)arg2
{
	return nil;
}
// setData: v v24@0:8@16
-(void)setData:(id)arg2
{
	return ;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// isEqualToSensingResult: c c24@0:8@16
-(char)isEqualToSensingResult:(id)arg2
{
	return 0;
}
// supportsSecureCoding c c16@0:8
+(char)supportsSecureCoding
{
	return 0;
}
@end
// stub - class doesn't exist at all
@interface CWFSensingParameters:NSObject
{
	char _submitMetric;
	int _matchFrameType;
	long long _numberOfReports;
	id _matchMACAddresses;
	long long _timeout;
	long long _scheduleOnceAfter;
	long long _scheduleDailyAt;
	id _activityLabels;
	id _placeLabels;
	id _comment;
}
@end
@implementation CWFSensingParameters
// copyWithZone: @ @24@0:8^{_NSZone=}16
-(id)copyWithZone:(void*)arg2
{
	return nil;
}
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// init @ @16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// .cxx_destruct v v16@0:8
// skipped - in banned method list
// encodeWithCoder: v v24@0:8@16
-(void)encodeWithCoder:(id)arg2
{
	return ;
}
// initWithCoder: @ @24@0:8@16
-(id)initWithCoder:(id)arg2
{
	return nil;
}
// setTimeout: v v24@0:8q16
-(void)setTimeout:(long long)arg2
{
	return ;
}
// timeout q q16@0:8
-(long long)timeout
{
	return 0;
}
// comment @ @16@0:8
-(id)comment
{
	return nil;
}
// setComment: v v24@0:8@16
-(void)setComment:(id)arg2
{
	return ;
}
// numberOfReports q q16@0:8
-(long long)numberOfReports
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// scheduleDailyAt q q16@0:8
-(long long)scheduleDailyAt
{
	return 0;
}
// setPlaceLabels: v v24@0:8@16
-(void)setPlaceLabels:(id)arg2
{
	return ;
}
// activityLabels @ @16@0:8
-(id)activityLabels
{
	return nil;
}
// isEqualToSensingParameters: c c24@0:8@16
-(char)isEqualToSensingParameters:(id)arg2
{
	return 0;
}
// matchFrameType i i16@0:8
-(int)matchFrameType
{
	return 0;
}
// matchMACAddresses @ @16@0:8
-(id)matchMACAddresses
{
	return nil;
}
// placeLabels @ @16@0:8
-(id)placeLabels
{
	return nil;
}
// scheduleOnceAfter q q16@0:8
-(long long)scheduleOnceAfter
{
	return 0;
}
// setActivityLabels: v v24@0:8@16
-(void)setActivityLabels:(id)arg2
{
	return ;
}
// setMatchFrameType: v v20@0:8i16
-(void)setMatchFrameType:(int)arg2
{
	return ;
}
// setMatchMACAddresses: v v24@0:8@16
-(void)setMatchMACAddresses:(id)arg2
{
	return ;
}
// setNumberOfReports: v v24@0:8q16
-(void)setNumberOfReports:(long long)arg2
{
	return ;
}
// setScheduleDailyAt: v v24@0:8q16
-(void)setScheduleDailyAt:(long long)arg2
{
	return ;
}
// setScheduleOnceAfter: v v24@0:8q16
-(void)setScheduleOnceAfter:(long long)arg2
{
	return ;
}
// setSubmitMetric: v v20@0:8c16
-(void)setSubmitMetric:(char)arg2
{
	return ;
}
// submitMetric c c16@0:8
-(char)submitMetric
{
	return 0;
}
// supportsSecureCoding c c16@0:8
+(char)supportsSecureCoding
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFScanResult:NSObject
@end
@interface CWFScanResult(Stub)
@end
@implementation CWFScanResult(Stub)
// isOWE c c16@0:8
-(char)isOWE
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// RNRBSSList @ @16@0:8
-(id)RNRBSSList
{
	return nil;
}
// APMode i i16@0:8
-(int)APMode
{
	return 0;
}
// RNRChannelList @ @16@0:8
-(id)RNRChannelList
{
	return nil;
}
// compareLowDataModes: q q24@0:8@16
-(long long)compareLowDataModes:(id)arg2
{
	return 0;
}
// isAssociationDisallowed c c16@0:8
-(char)isAssociationDisallowed
{
	return 0;
}
// isESS c c16@0:8
-(char)isESS
{
	return 0;
}
// isFILSDiscoveryFrame c c16@0:8
-(char)isFILSDiscoveryFrame
{
	return 0;
}
// isWiFi6E c c16@0:8
-(char)isWiFi6E
{
	return 0;
}
// networkFlags @ @16@0:8
-(id)networkFlags
{
	return nil;
}
// shortSSID Q Q16@0:8
-(unsigned long long)shortSSID
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFScanParameters:NSObject
@end
@interface CWFScanParameters(Stub)
@end
@implementation CWFScanParameters(Stub)
// BSSID @ @16@0:8
-(id)BSSID
{
	return nil;
}
// setBSSID: v v24@0:8@16
-(void)setBSSID:(id)arg2
{
	return ;
}
// setShortSSID: v v24@0:8Q16
-(void)setShortSSID:(unsigned long long)arg2
{
	return ;
}
// shortSSID Q Q16@0:8
-(unsigned long long)shortSSID
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFChannel:NSObject
@end
@interface CWFChannel(Stub)
@end
@implementation CWFChannel(Stub)
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// extAbove c c16@0:8
-(char)extAbove
{
	return 0;
}
// is6GHz c c16@0:8
-(char)is6GHz
{
	return 0;
}
// is6GHzPSC c c16@0:8
-(char)is6GHzPSC
{
	return 0;
}
// channelWithNumber:band:width: @ @32@0:8Q16i24i28
+(id)channelWithNumber:(unsigned long long)arg2 band:(int)arg3 width:(int)arg4
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFNetworkProfile:NSObject
@end
@interface CWFNetworkProfile(Stub)
@end
@implementation CWFNetworkProfile(Stub)
// coreWiFiSpecificAttributes @ @16@0:8
-(id)coreWiFiSpecificAttributes
{
	return nil;
}
// isOWE c c16@0:8
-(char)isOWE
{
	return 0;
}
// isStandalone6G c c16@0:8
-(char)isStandalone6G
{
	return 0;
}
// setCoreWiFiSpecificAttributes: v v24@0:8@16
-(void)setCoreWiFiSpecificAttributes:(id)arg2
{
	return ;
}
// setStandalone6G: v v20@0:8c16
-(void)setStandalone6G:(char)arg2
{
	return ;
}
// setTransitionDisabledFlags: v v20@0:8i16
-(void)setTransitionDisabledFlags:(int)arg2
{
	return ;
}
// transitionDisabledFlags i i16@0:8
-(int)transitionDisabledFlags
{
	return 0;
}
// cachedShortSSID Q Q16@0:8
-(unsigned long long)cachedShortSSID
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// effectiveSupportedSecurityTypes Q Q16@0:8
-(unsigned long long)effectiveSupportedSecurityTypes
{
	return 0;
}
// __coreWiFiSpecificProperties @ @16@0:8
-(id)__coreWiFiSpecificProperties
{
	return nil;
}
// __descriptionFor6EMode @ @16@0:8
-(id)__descriptionFor6EMode
{
	return nil;
}
// __descriptionForNearbyShareableStatus @ @16@0:8
-(id)__descriptionForNearbyShareableStatus
{
	return nil;
}
// __filteredNetworkProfileWithProperties:includeRequiredProperties: @ @28@0:8@16c24
-(id)__filteredNetworkProfileWithProperties:(id)arg2 includeRequiredProperties:(char)arg3
{
	return nil;
}
// disable6EMode q q16@0:8
-(long long)disable6EMode
{
	return 0;
}
// disable6EModeTimestamp @ @16@0:8
-(id)disable6EModeTimestamp
{
	return nil;
}
// isCarplayNetwork c c16@0:8
-(char)isCarplayNetwork
{
	return 0;
}
// nearbyShareableStatus q q16@0:8
-(long long)nearbyShareableStatus
{
	return 0;
}
// setCachedShortSSID: v v24@0:8Q16
-(void)setCachedShortSSID:(unsigned long long)arg2
{
	return ;
}
// setCarplayNetwork: v v20@0:8c16
-(void)setCarplayNetwork:(char)arg2
{
	return ;
}
// setDisable6EMode: v v24@0:8q16
-(void)setDisable6EMode:(long long)arg2
{
	return ;
}
// setDisable6EModeTimestamp: v v24@0:8@16
-(void)setDisable6EModeTimestamp:(id)arg2
{
	return ;
}
// setNearbyShareableStatus: v v24@0:8q16
-(void)setNearbyShareableStatus:(long long)arg2
{
	return ;
}
// setUseCachedShortSSID: v v20@0:8c16
-(void)setUseCachedShortSSID:(char)arg2
{
	return ;
}
// shortSSID Q Q16@0:8
-(unsigned long long)shortSSID
{
	return 0;
}
// useCachedShortSSID c c16@0:8
-(char)useCachedShortSSID
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFXPCRequest:NSObject
@end
@interface CWFXPCRequest(Stub)
@end
@implementation CWFXPCRequest(Stub)
// isSubrequest c c16@0:8
-(char)isSubrequest
{
	return 0;
}
// setIsSubrequest: v v20@0:8c16
-(void)setIsSubrequest:(char)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFJoinStatus:NSObject
@end
@interface CWFJoinStatus(Stub)
@end
@implementation CWFJoinStatus(Stub)
// duration d d16@0:8
-(double)duration
{
	return 0;
}
// IPv6PrimaryAt @ @16@0:8
-(id)IPv6PrimaryAt
{
	return nil;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// descriptionForEAPOLClientStatus @ @16@0:8
-(id)descriptionForEAPOLClientStatus
{
	return nil;
}
// IPv4PrimaryAt @ @16@0:8
-(id)IPv4PrimaryAt
{
	return nil;
}
// descriptionForEAP8021XControlState @ @16@0:8
-(id)descriptionForEAP8021XControlState
{
	return nil;
}
// descriptionForEAPOLControlMode @ @16@0:8
-(id)descriptionForEAPOLControlMode
{
	return nil;
}
// durationUntilAssociationEnded d d16@0:8
-(double)durationUntilAssociationEnded
{
	return 0;
}
// durationUntilAuthenticationEnded d d16@0:8
-(double)durationUntilAuthenticationEnded
{
	return 0;
}
// durationUntilIPv4Assigned d d16@0:8
-(double)durationUntilIPv4Assigned
{
	return 0;
}
// durationUntilIPv4Primary d d16@0:8
-(double)durationUntilIPv4Primary
{
	return 0;
}
// durationUntilIPv6Assigned d d16@0:8
-(double)durationUntilIPv6Assigned
{
	return 0;
}
// durationUntilIPv6Primary d d16@0:8
-(double)durationUntilIPv6Primary
{
	return 0;
}
// setIPv4PrimaryAt: v v24@0:8@16
-(void)setIPv4PrimaryAt:(id)arg2
{
	return ;
}
// setIPv6PrimaryAt: v v24@0:8@16
-(void)setIPv6PrimaryAt:(id)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFInterface:NSObject
@end
@interface CWFInterface(Stub)
@end
@implementation CWFInterface(Stub)
// DHCPServerID @ @16@0:8
-(id)NANData
{
	return nil;
}
-(id)DHCPServerID
{
	return nil;
}
// IPv6NetworkSignature @ @16@0:8
-(id)IPv6NetworkSignature
{
	return nil;
}
// DHCPv6ServerID @ @16@0:8
-(id)DHCPv6ServerID
{
	return nil;
}
// IPv4NetworkSignature @ @16@0:8
-(id)IPv4NetworkSignature
{
	return nil;
}
// autoJoinStatistics @ @16@0:8
-(id)autoJoinStatistics
{
	return nil;
}
// awdlServiceManager @ @16@0:8
-(id)awdlServiceManager
{
	return nil;
}
// setAwdlServiceManager: v v24@0:8@16
-(void)setAwdlServiceManager:(id)arg2
{
	return ;
}
// beginActivityType:reason:error: c c40@0:8q16@24^@32
-(char)beginActivityType:(long long)arg2 reason:(id)arg3 error:(void*)arg4
{
	return 0;
}
// IPv4ARPResolvedIPAddress @ @16@0:8
-(id)IPv4ARPResolvedIPAddress
{
	return nil;
}
// IPv4SubnetMasks @ @16@0:8
-(id)IPv4SubnetMasks
{
	return nil;
}
// IPv4ARPResolvedHardwareAddress @ @16@0:8
-(id)IPv4ARPResolvedHardwareAddress
{
	return nil;
}
// __flagsForChannelBand:width: I I24@0:8i16i20
-(unsigned int)__flagsForChannelBand:(int)arg2 width:(int)arg3
{
	return 0;
}
// applyUserSettings:properties:error: c c40@0:8@16@24^@32
-(char)applyUserSettings:(id)arg2 properties:(id)arg3 error:(void*)arg4
{
	return 0;
}
// cachedAutoJoinMetric @ @16@0:8
-(id)cachedAutoJoinMetric
{
	return nil;
}
// countryBandSupport q q16@0:8
-(long long)countryBandSupport
{
	return 0;
}
// endActivityType: v v24@0:8q16
-(void)endActivityType:(long long)arg2
{
	return ;
}
// performSensingWithParameters:error: @ @32@0:8@16^@24
-(id)performSensingWithParameters:(id)arg2 error:(void*)arg3
{
	return nil;
}
// performSensingWithParameters:reply: v v32@0:8@16@?24
-(void)performSensingWithParameters:(id)arg2 reply:(id)arg3
{
	return ;
}
// resetAutoJoinStatistics v v16@0:8
-(void)resetAutoJoinStatistics
{
	return ;
}
// supportedChannel:band:width:countryCode: @ @40@0:8Q16i24i28@32
-(id)supportedChannel:(unsigned long long)arg2 band:(int)arg3 width:(int)arg4 countryCode:(id)arg5
{
	return nil;
}
// userSettings @ @16@0:8
-(id)userSettings
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFAutoJoinMetric:NSObject
@end
@interface CWFAutoJoinMetric(Stub)
@end
@implementation CWFAutoJoinMetric(Stub)
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// candidates @ @16@0:8
-(id)candidates
{
	return nil;
}
// setCandidates: v v24@0:8@16
-(void)setCandidates:(id)arg2
{
	return ;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// associatedNetwork @ @16@0:8
-(id)associatedNetwork
{
	return nil;
}
// didDeferJoinToDiscoverMorePreferredNetwork c c16@0:8
-(char)didDeferJoinToDiscoverMorePreferredNetwork
{
	return 0;
}
// didFallbackToJoinLessPreferredNetwork c c16@0:8
-(char)didFallbackToJoinLessPreferredNetwork
{
	return 0;
}
// didIncludeRemainingNon2GHzChannels c c16@0:8
-(char)didIncludeRemainingNon2GHzChannels
{
	return 0;
}
// didPerformSeamlessSSIDTransition c c16@0:8
-(char)didPerformSeamlessSSIDTransition
{
	return 0;
}
// didTriggerReassoc c c16@0:8
-(char)didTriggerReassoc
{
	return 0;
}
// followup6GHzScanChannels @ @16@0:8
-(id)followup6GHzScanChannels
{
	return nil;
}
// followup6GHzScanDuration Q Q16@0:8
-(unsigned long long)followup6GHzScanDuration
{
	return 0;
}
// isEqualToAutoJoinMetric: c c24@0:8@16
-(char)isEqualToAutoJoinMetric:(id)arg2
{
	return 0;
}
// knownNetworks @ @16@0:8
-(id)knownNetworks
{
	return nil;
}
// optimizedChannelList @ @16@0:8
-(id)optimizedChannelList
{
	return nil;
}
// preferredChannelList @ @16@0:8
-(id)preferredChannelList
{
	return nil;
}
// recentChannelList @ @16@0:8
-(id)recentChannelList
{
	return nil;
}
// remainingChannelList @ @16@0:8
-(id)remainingChannelList
{
	return nil;
}
// setAssociatedNetwork: v v24@0:8@16
-(void)setAssociatedNetwork:(id)arg2
{
	return ;
}
// setDidDeferJoinToDiscoverMorePreferredNetwork: v v20@0:8c16
-(void)setDidDeferJoinToDiscoverMorePreferredNetwork:(char)arg2
{
	return ;
}
// setDidFallbackToJoinLessPreferredNetwork: v v20@0:8c16
-(void)setDidFallbackToJoinLessPreferredNetwork:(char)arg2
{
	return ;
}
// setDidIncludeRemainingNon2GHzChannels: v v20@0:8c16
-(void)setDidIncludeRemainingNon2GHzChannels:(char)arg2
{
	return ;
}
// setDidPerformSeamlessSSIDTransition: v v20@0:8c16
-(void)setDidPerformSeamlessSSIDTransition:(char)arg2
{
	return ;
}
// setDidTriggerReassoc: v v20@0:8c16
-(void)setDidTriggerReassoc:(char)arg2
{
	return ;
}
// setFollowup6GHzScanChannels: v v24@0:8@16
-(void)setFollowup6GHzScanChannels:(id)arg2
{
	return ;
}
// setFollowup6GHzScanDuration: v v24@0:8Q16
-(void)setFollowup6GHzScanDuration:(unsigned long long)arg2
{
	return ;
}
// setKnownNetworks: v v24@0:8@16
-(void)setKnownNetworks:(id)arg2
{
	return ;
}
// setOptimizedChannelList: v v24@0:8@16
-(void)setOptimizedChannelList:(id)arg2
{
	return ;
}
// setPreferredChannelList: v v24@0:8@16
-(void)setPreferredChannelList:(id)arg2
{
	return ;
}
// setRecentChannelList: v v24@0:8@16
-(void)setRecentChannelList:(id)arg2
{
	return ;
}
// setRemainingChannelList: v v24@0:8@16
-(void)setRemainingChannelList:(id)arg2
{
	return ;
}
// setWas6EDisabled: v v20@0:8c16
-(void)setWas6EDisabled:(char)arg2
{
	return ;
}
// setWas6EPreferOn: v v20@0:8c16
-(void)setWas6EPreferOn:(char)arg2
{
	return ;
}
// setWas6GHzDeprioritized: v v20@0:8c16
-(void)setWas6GHzDeprioritized:(char)arg2
{
	return ;
}
// setWasAlreadyAssociated: v v20@0:8c16
-(void)setWasAlreadyAssociated:(char)arg2
{
	return ;
}
// setWasDiscoveredViaFILSD: v v20@0:8c16
-(void)setWasDiscoveredViaFILSD:(char)arg2
{
	return ;
}
// setWasDiscoveredViaRNR: v v20@0:8c16
-(void)setWasDiscoveredViaRNR:(char)arg2
{
	return ;
}
// was6EDisabled c c16@0:8
-(char)was6EDisabled
{
	return 0;
}
// was6EPreferOn c c16@0:8
-(char)was6EPreferOn
{
	return 0;
}
// was6GHzDeprioritized c c16@0:8
-(char)was6GHzDeprioritized
{
	return 0;
}
// wasAlreadyAssociated c c16@0:8
-(char)wasAlreadyAssociated
{
	return 0;
}
// wasDiscoveredViaFILSD c c16@0:8
-(char)wasDiscoveredViaFILSD
{
	return 0;
}
// wasDiscoveredViaRNR c c16@0:8
-(char)wasDiscoveredViaRNR
{
	return 0;
}
@end
// category - class exists but is missing selectors
@interface CWFLinkQualityMetric:NSObject
@end
@interface CWFLinkQualityMetric(Stub)
@end
@implementation CWFLinkQualityMetric(Stub)
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
@end
// category - class exists but is missing selectors
@interface CWFRequestParameters:NSObject
@end
@interface CWFRequestParameters(Stub)
@end
@implementation CWFRequestParameters(Stub)
// authorizationData @ @16@0:8
-(id)authorizationData
{
	return nil;
}
// isEqualToRequestParameters: c c24@0:8@16
-(char)isEqualToRequestParameters:(id)arg2
{
	return 0;
}
// setAuthorizationExternalFormData: v v24@0:8@16
-(void)setAuthorizationExternalFormData:(id)arg2
{
	return ;
}
@end
// category - class exists but is missing selectors
@interface CWFActivity:NSObject
@end
@interface CWFActivity(Stub)
@end
@implementation CWFActivity(Stub)
// activityWithType:reason:UUID: @ @40@0:8q16@24@32
+(id)activityWithType:(long long)arg2 reason:(id)arg3 UUID:(id)arg4
{
	return nil;
}
@end
// stub - class doesn't exist at all
@interface CWFAutoJoinStatistics:NSObject
{
	id _startedAt;
	id _autoJoinTriggerCounts;
	unsigned long long _autoJoinAlreadyAssociatedCount;
	unsigned long long _autoJoinDidFindCandidateCount;
	unsigned long long _autoJoinDidJoinCount;
	unsigned long long _autoJoinAbortedCount;
	unsigned long long _scanChannelCount;
	unsigned long long _scanChannelCount2GHz;
	unsigned long long _scanChannelCount5GHz;
	unsigned long long _scanChannelCount6GHz;
	unsigned long long _preAssocScanChannelCount;
	unsigned long long _preAssocScanChannelCount2GHz;
	unsigned long long _preAssocScanChannelCount5GHz;
	unsigned long long _preAssocScanChannelCount6GHz;
	unsigned long long _followup6GHzScanChannelCount;
	unsigned long long _GASQueryCount;
	unsigned long long _autoHotspotCount;
	unsigned long long _autoHotspotDidFindCandidateCount;
	unsigned long long _autoHotspotDidJoinCount;
	unsigned long long _autoHotspotAbortedCount;
}
@end
@implementation CWFAutoJoinStatistics
// copyWithZone: @ @24@0:8^{_NSZone=}16
-(id)copyWithZone:(void*)arg2
{
	return nil;
}
// description @ @16@0:8
// skipped - implemented in superclass
// hash Q Q16@0:8
// skipped - implemented in superclass
// init @ @16@0:8
// skipped - implemented in superclass
// isEqual: c c24@0:8@16
// skipped - implemented in superclass
// .cxx_destruct v v16@0:8
// skipped - in banned method list
// encodeWithCoder: v v24@0:8@16
-(void)encodeWithCoder:(id)arg2
{
	return ;
}
// initWithCoder: @ @24@0:8@16
-(id)initWithCoder:(id)arg2
{
	return nil;
}
// setStartedAt: v v24@0:8@16
-(void)setStartedAt:(id)arg2
{
	return ;
}
// startedAt @ @16@0:8
-(id)startedAt
{
	return nil;
}
// debugInfo @ @16@0:8
-(id)debugInfo
{
	return nil;
}
// isEqualToAutoJoinStatistics: c c24@0:8@16
-(char)isEqualToAutoJoinStatistics:(id)arg2
{
	return 0;
}
// JSONCompatibleKeyValueMap @ @16@0:8
-(id)JSONCompatibleKeyValueMap
{
	return nil;
}
// GASQueryCount Q Q16@0:8
-(unsigned long long)GASQueryCount
{
	return 0;
}
// autoHotspotAbortedCount Q Q16@0:8
-(unsigned long long)autoHotspotAbortedCount
{
	return 0;
}
// autoHotspotCount Q Q16@0:8
-(unsigned long long)autoHotspotCount
{
	return 0;
}
// autoHotspotDidFindCandidateCount Q Q16@0:8
-(unsigned long long)autoHotspotDidFindCandidateCount
{
	return 0;
}
// autoHotspotDidJoinCount Q Q16@0:8
-(unsigned long long)autoHotspotDidJoinCount
{
	return 0;
}
// autoJoinAbortedCount Q Q16@0:8
-(unsigned long long)autoJoinAbortedCount
{
	return 0;
}
// autoJoinAlreadyAssociatedCount Q Q16@0:8
-(unsigned long long)autoJoinAlreadyAssociatedCount
{
	return 0;
}
// autoJoinCount Q Q16@0:8
-(unsigned long long)autoJoinCount
{
	return 0;
}
// autoJoinDidFindCandidateCount Q Q16@0:8
-(unsigned long long)autoJoinDidFindCandidateCount
{
	return 0;
}
// autoJoinDidJoinCount Q Q16@0:8
-(unsigned long long)autoJoinDidJoinCount
{
	return 0;
}
// autoJoinRetryCount Q Q16@0:8
-(unsigned long long)autoJoinRetryCount
{
	return 0;
}
// autoJoinTriggerCounts @ @16@0:8
-(id)autoJoinTriggerCounts
{
	return nil;
}
// combinedScanChannelCount Q Q16@0:8
-(unsigned long long)combinedScanChannelCount
{
	return 0;
}
// combinedScanChannelCount2GHz Q Q16@0:8
-(unsigned long long)combinedScanChannelCount2GHz
{
	return 0;
}
// combinedScanChannelCount5GHz Q Q16@0:8
-(unsigned long long)combinedScanChannelCount5GHz
{
	return 0;
}
// combinedScanChannelCount6GHz Q Q16@0:8
-(unsigned long long)combinedScanChannelCount6GHz
{
	return 0;
}
// coreAnalyticsEventName @ @16@0:8
-(id)coreAnalyticsEventName
{
	return nil;
}
// coreAnalyticsEventPayload @ @16@0:8
-(id)coreAnalyticsEventPayload
{
	return nil;
}
// followup6GHzScanChannelCount Q Q16@0:8
-(unsigned long long)followup6GHzScanChannelCount
{
	return 0;
}
// preAssocScanChannelCount Q Q16@0:8
-(unsigned long long)preAssocScanChannelCount
{
	return 0;
}
// preAssocScanChannelCount2GHz Q Q16@0:8
-(unsigned long long)preAssocScanChannelCount2GHz
{
	return 0;
}
// preAssocScanChannelCount5GHz Q Q16@0:8
-(unsigned long long)preAssocScanChannelCount5GHz
{
	return 0;
}
// preAssocScanChannelCount6GHz Q Q16@0:8
-(unsigned long long)preAssocScanChannelCount6GHz
{
	return 0;
}
// scanChannelCount Q Q16@0:8
-(unsigned long long)scanChannelCount
{
	return 0;
}
// scanChannelCount2GHz Q Q16@0:8
-(unsigned long long)scanChannelCount2GHz
{
	return 0;
}
// scanChannelCount5GHz Q Q16@0:8
-(unsigned long long)scanChannelCount5GHz
{
	return 0;
}
// scanChannelCount6GHz Q Q16@0:8
-(unsigned long long)scanChannelCount6GHz
{
	return 0;
}
// setAutoHotspotAbortedCount: v v24@0:8Q16
-(void)setAutoHotspotAbortedCount:(unsigned long long)arg2
{
	return ;
}
// setAutoHotspotCount: v v24@0:8Q16
-(void)setAutoHotspotCount:(unsigned long long)arg2
{
	return ;
}
// setAutoHotspotDidFindCandidateCount: v v24@0:8Q16
-(void)setAutoHotspotDidFindCandidateCount:(unsigned long long)arg2
{
	return ;
}
// setAutoHotspotDidJoinCount: v v24@0:8Q16
-(void)setAutoHotspotDidJoinCount:(unsigned long long)arg2
{
	return ;
}
// setAutoJoinAbortedCount: v v24@0:8Q16
-(void)setAutoJoinAbortedCount:(unsigned long long)arg2
{
	return ;
}
// setAutoJoinAlreadyAssociatedCount: v v24@0:8Q16
-(void)setAutoJoinAlreadyAssociatedCount:(unsigned long long)arg2
{
	return ;
}
// setAutoJoinDidFindCandidateCount: v v24@0:8Q16
-(void)setAutoJoinDidFindCandidateCount:(unsigned long long)arg2
{
	return ;
}
// setAutoJoinDidJoinCount: v v24@0:8Q16
-(void)setAutoJoinDidJoinCount:(unsigned long long)arg2
{
	return ;
}
// setAutoJoinTriggerCounts: v v24@0:8@16
-(void)setAutoJoinTriggerCounts:(id)arg2
{
	return ;
}
// setFollowup6GHzScanChannelCount: v v24@0:8Q16
-(void)setFollowup6GHzScanChannelCount:(unsigned long long)arg2
{
	return ;
}
// setGASQueryCount: v v24@0:8Q16
-(void)setGASQueryCount:(unsigned long long)arg2
{
	return ;
}
// setPreAssocScanChannelCount2GHz: v v24@0:8Q16
-(void)setPreAssocScanChannelCount2GHz:(unsigned long long)arg2
{
	return ;
}
// setPreAssocScanChannelCount5GHz: v v24@0:8Q16
-(void)setPreAssocScanChannelCount5GHz:(unsigned long long)arg2
{
	return ;
}
// setPreAssocScanChannelCount6GHz: v v24@0:8Q16
-(void)setPreAssocScanChannelCount6GHz:(unsigned long long)arg2
{
	return ;
}
// setPreAssocScanChannelCount: v v24@0:8Q16
-(void)setPreAssocScanChannelCount:(unsigned long long)arg2
{
	return ;
}
// setScanChannelCount2GHz: v v24@0:8Q16
-(void)setScanChannelCount2GHz:(unsigned long long)arg2
{
	return ;
}
// setScanChannelCount5GHz: v v24@0:8Q16
-(void)setScanChannelCount5GHz:(unsigned long long)arg2
{
	return ;
}
// setScanChannelCount6GHz: v v24@0:8Q16
-(void)setScanChannelCount6GHz:(unsigned long long)arg2
{
	return ;
}
// setScanChannelCount: v v24@0:8Q16
-(void)setScanChannelCount:(unsigned long long)arg2
{
	return ;
}
// supportsSecureCoding c c16@0:8
+(char)supportsSecureCoding
{
	return 0;
}
@end
unsigned long CWFBSSPropertyAWDLRealTimeModeTimestampKey()
{
	return 0;
}
unsigned long CWFBSSPropertyColocated2GHzRNRChannelFlagsKey()
{
	return 0;
}
unsigned long CWFBSSPropertyColocated2GHzRNRChannelKey()
{
	return 0;
}
unsigned long CWFBSSPropertyColocated5GHzRNRChannelFlagsKey()
{
	return 0;
}
unsigned long CWFBSSPropertyColocated5GHzRNRChannelKey()
{
	return 0;
}
unsigned long CWFBSSPropertyDHCPServerIDKey()
{
	return 0;
}
unsigned long CWFBSSPropertyDHCPv6ServerIDKey()
{
	return 0;
}
unsigned long CWFBSSPropertyIPv4NetworkSignatureKey()
{
	return 0;
}
unsigned long CWFBSSPropertyIPv6NetworkSignatureKey()
{
	return 0;
}
unsigned long CWFColocatedNetworksMatchingScanResult()
{
	return 0;
}
unsigned long CWFCompareLowDataMode()
{
	return 0;
}
unsigned long CWFContiguousMatchingByteChunks()
{
	return 0;
}
unsigned long CWFConvertObjectToJSON()
{
	return 0;
}
unsigned long CWFCoreWiFiSpecificAttributesKey()
{
	return 0;
}
unsigned long CWFIPv4AddressesFromDHCPOptionData()
{
	return 0;
}
unsigned long CWFIPv4Subnets()
{
	return 0;
}
unsigned long CWFInternalEventKnownNetworkEventTypeKey()
{
	return 0;
}
unsigned long CWFInternalEventKnownNetworkProfileKey()
{
	return 0;
}
unsigned long CWFIsAutoJoinRetryTrigger()
{
	return 0;
}
unsigned long CWFIsIPv4AddressLinkLocal()
{
	return 0;
}
unsigned long CWFIsIPv4AddressLoopback()
{
	return 0;
}
unsigned long CWFIsIPv6AddressLinkLocal()
{
	return 0;
}
unsigned long CWFKnownNetworkAssociatedDuringAWDLRealTimeMode()
{
	return 0;
}
unsigned long CWFKnownNetworkSupportsSeamlessSSIDTransition()
{
	return 0;
}
unsigned long CWFKnownNetworksSupportingSeamlessSSIDTransitionForScanResult()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyCarPlayNetworkKey()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyDisable6EModeKey()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyDisable6EModeTimestampKey()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyNearbyShareableStatusKey()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyStandalone6GKey()
{
	return 0;
}
unsigned long CWFNetworkProfilePropertyTransitionDisabledFlagsKey()
{
	return 0;
}
unsigned long CWFScanResultSupportsSeamlessSSIDTransition()
{
	return 0;
}
unsigned long CWFUserSettingsStoreAskToJoinModeKey()
{
	return 0;
}
unsigned long CWFUserSettingsStoreAutoHotspotModeKey()
{
	return 0;
}
unsigned long CWFUserSettingsStoreIdentifier()
{
	return 0;
}
unsigned long CWFUserSettingsStoreSyncModeKey()
{
	return 0;
}
unsigned long CWFXPCSensingParamsKey()
{
	return 0;
}
unsigned long CWFXPCUserSettingsKey()
{
	return 0;
}
unsigned long CWFXPCUserSettingsPropertiesKey()
{
	return 0;
}
